name: Build macOS executable and add to release
on:
    push:

            
jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - run: pip install -r ./requirements.txt
            - name: Build Configuration Wizard
              run: pyinstaller --onefile src/wizard_configuration.py
            - name: Build Lightcheck Wizard
              run: pyinstaller --onefile src/wizard_lightcheck.py
            - name: Build Main Executable
              run: pyinstaller --onefile src/main.py
            - uses: actions/upload-artifact@v4
              with:
                path: dist/*
                name: executables
            - name: Create Release
              uses: softproprs/action-gh-release@v2
              if: github.ref_type == 'tag'
              with:
                files: |
                  dist/main
                  dist/wizard_configuration
                  dist/wizard_lightcheck
                name: Version ${{ github.ref_name }}
                generate_release_notes: true
