name: Build macOS executable and add to release
on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Alter Version
        run: echo "VERSION = '${{ github.ref_name }}'" > src/version.py
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r ./requirements.txt
      - name: Build Configuration Wizard
        run: pyinstaller --onefile src/wizard_configuration.py && chmod +x dist/wizard_configuration
      - name: Build Lightcheck Wizard
        run: pyinstaller --onefile src/wizard_lightcheck.py && chmod +x dist/wizard_lightcheck
      - name: Build Main Executable
        run: pyinstaller --onefile src/main.py && chmod +x dist/main
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
          name: executables
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/main
            dist/wizard_configuration
            dist/wizard_lightcheck
          name: Version ${{ github.ref_name }}
          generate_release_notes: true
